### ISSUE TITLE
Weird ass crash on 1.12 with this mod and loottweaker

### ISSUE THREAD

**Issue by Sunconure11** [CursedFlames/BountifulBaubles#29] opened 2020-04-19 20:29 UTC
https://paste.dimdev.org/uyosukohax.mccrash

This pretty much cripples any attempt at starting up a world. I don't know if you're still supporting 1.12, but I'd advise at least fixing this.

**Comment by Daomephsta** [comment] 2020-04-19 22:52
This is caused by a typo here
https://github.com/CursedFlames/BountifulBaubles/blob/master/src/main/java/cursedflames/bountifulbaubles/loot/ModLoot.java#L134

Duplicate entry names are invalid according to Forge, however for some reason it checks for duplicate names when entries are added via `LootPool.addEntry()`, but not in the constructor.
LootTweaker's internal mutable loot data structures properly enforce unique pool and entry names.

@Sunconure11 
You can get worlds to launch for now by not editing `minecraft:chests/simple_dungeon` in your scripts, as LootTweaker only creates the mutable data structures for tables it has been asked to edit.
Alternatively, downgrade your LootTweaker installation to 0.1.6. It won't cause this crash because it doesn't include the internal mutable data structures, however it of course still has the bugs that were fixed in 0.1.7.

**Comment by Sunconure11** [comment] 2020-04-19 23:38
@CursedFlames

**Comment by CursedFlames** [comment] 2020-04-19 23:47
Uh yeah, I'll fix this whenever I can get my 1.12 dev env working again

**Closed as completed** 2020-05-09 07:23 UTC
